'use client';
import { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import toast from 'react-hot-toast';
import { invoiceAPI } from '@/lib/api';

export default function InvoiceDetailPage() {
  const { id } = useParams();
  const router = useRouter();
  const [invoice, setInvoice] = useState(null);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(false);

  useEffect(() => {
    invoiceAPI.getById(id)
      .then(res => setInvoice(res.data))
      .catch(() => { toast.error('Invoice not found'); router.push('/dashboard/invoices'); })
      .finally(() => setLoading(false));
  }, [id, router]);

  const downloadPDF = async () => {
    setDownloading(true);
    try {
      const { default: jsPDF } = await import('jspdf');
      const { default: autoTable } = await import('jspdf-autotable');

      const doc = new jsPDF();
      const inv = invoice;
      const c = inv.customer;

      // Header
      doc.setFillColor(108, 99, 255);
      doc.rect(0, 0, 210, 40, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(24);
      doc.setFont('helvetica', 'bold');
      doc.text('CRM PRO', 14, 18);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.text('Customer Relationship Management', 14, 26);
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text('INVOICE', 145, 20);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.text(inv.invoiceNumber, 145, 29);

      // Reset color
      doc.setTextColor(20, 20, 30);

      // Bill To
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text('BILL TO:', 14, 55);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      doc.text(c?.name || '—', 14, 63);
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 120);
      doc.text(c?.email || '', 14, 70);
      doc.text(c?.phone || '', 14, 76);
      doc.text(c?.company || '', 14, 82);
      doc.text(c?.address || '', 14, 88);

      // Invoice Info
      doc.setTextColor(20, 20, 30);
      doc.setFont('helvetica', 'bold');
      doc.text('INVOICE DATE:', 130, 55);
      doc.text('DUE DATE:', 130, 63);
      doc.text('STATUS:', 130, 71);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 120);
      doc.text(new Date(inv.createdAt).toLocaleDateString('en-PK'), 175, 55);
      doc.text(inv.dueDate ? new Date(inv.dueDate).toLocaleDateString('en-PK') : 'N/A', 175, 63);
      doc.text(inv.status, 175, 71);

      // Items table
      doc.setTextColor(20, 20, 30);
      autoTable(doc, {
        startY: 100,
        head: [['#', 'Description', 'Qty', 'Unit Price (PKR)', 'Total (PKR)']],
        body: inv.items.map((item, i) => [
          i + 1,
          item.description,
          item.quantity,
          item.unitPrice.toLocaleString(),
          item.total.toLocaleString(),
        ]),
        headStyles: { fillColor: [108, 99, 255], textColor: 255, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [245, 245, 255] },
        styles: { fontSize: 10, cellPadding: 6 },
        columnStyles: { 0: { cellWidth: 12 }, 1: { cellWidth: 80 } },
      });

      const finalY = doc.lastAutoTable.finalY + 10;

      // Totals
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 120);
      doc.text('Subtotal:', 140, finalY);
      doc.text(`PKR ${inv.subtotal.toLocaleString()}`, 175, finalY);
      doc.text('Tax:', 140, finalY + 8);
      doc.text(`PKR ${inv.tax.toLocaleString()}`, 175, finalY + 8);
      doc.setDrawColor(108, 99, 255);
      doc.line(130, finalY + 12, 200, finalY + 12);
      doc.setTextColor(20, 20, 30);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.text('TOTAL:', 140, finalY + 20);
      doc.setTextColor(0, 180, 140);
      doc.text(`PKR ${inv.total.toLocaleString()}`, 175, finalY + 20);

      // Notes
      if (inv.notes) {
        doc.setTextColor(100, 100, 120);
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(10);
        doc.text('Notes: ' + inv.notes, 14, finalY + 30);
      }

      // Footer
      doc.setFillColor(245, 245, 255);
      doc.rect(0, 275, 210, 25, 'F');
      doc.setTextColor(150, 150, 170);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.text('Thank you for your business!', 105, 283, { align: 'center' });
      doc.text('Generated by CRM Pro — Air University Final Term Project', 105, 290, { align: 'center' });

      doc.save(`${inv.invoiceNumber}.pdf`);
      toast.success('Invoice PDF downloaded!');
    } catch (err) {
      console.error(err);
      toast.error('Failed to generate PDF');
    } finally {
      setDownloading(false);
    }
  };

  if (loading) return <div className="loading"><div className="spinner" /><span>Loading invoice...</span></div>;
  if (!invoice) return null;

  const c = invoice.customer;

  return (
    <div>
      <div className="page-header">
        <div>
          <h1 className="page-title">{invoice.invoiceNumber}</h1>
          <p className="page-subtitle">{c?.name} · {new Date(invoice.createdAt).toLocaleDateString('en-PK', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
        </div>
        <div className="flex gap-3">
          <button className="btn btn-primary" onClick={downloadPDF} disabled={downloading}>
            {downloading ? <><span className="spinner" style={{ width: 16, height: 16 }} /> Generating...</> : '⬇️ Download PDF'}
          </button>
          <Link href="/dashboard/invoices" className="btn btn-secondary">← Back</Link>
        </div>
      </div>

      {/* Invoice preview card */}
      <div className="card" style={{ maxWidth: 820 }}>
        {/* Invoice header */}
        <div style={{ background: 'linear-gradient(135deg, var(--accent), var(--accent2))', padding: '28px 32px', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <div>
            <div style={{ fontFamily: 'Syne, sans-serif', fontSize: 24, fontWeight: 800, color: 'white' }}>CRM PRO</div>
            <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.7)', marginTop: 4 }}>Customer Relationship Management</div>
          </div>
          <div style={{ textAlign: 'right' }}>
            <div style={{ fontFamily: 'Syne, sans-serif', fontSize: 22, fontWeight: 700, color: 'white' }}>INVOICE</div>
            <div style={{ fontSize: 14, color: 'rgba(255,255,255,0.85)', marginTop: 4 }}>{invoice.invoiceNumber}</div>
          </div>
        </div>

        <div style={{ padding: 32 }}>
          {/* Bill to + Details */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 32, marginBottom: 32, paddingBottom: 24, borderBottom: '1px solid var(--border)' }}>
            <div>
              <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 8 }}>Bill To</div>
              <div style={{ fontWeight: 700, fontSize: 16 }}>{c?.name}</div>
              <div style={{ color: 'var(--text-muted)', fontSize: 13, marginTop: 4, lineHeight: 1.8 }}>
                {c?.email}<br />{c?.phone}<br />{c?.company}<br />{c?.address}
              </div>
            </div>
            <div style={{ textAlign: 'right' }}>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                {[
                  ['Date', new Date(invoice.createdAt).toLocaleDateString('en-PK')],
                  ['Due Date', invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString('en-PK') : 'N/A'],
                  ['Status', invoice.status],
                ].map(([label, val]) => (
                  <div key={label} style={{ display: 'flex', justifyContent: 'flex-end', gap: 16, fontSize: 13 }}>
                    <span style={{ color: 'var(--text-muted)' }}>{label}:</span>
                    <span style={{ fontWeight: 600 }}>{val}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Items */}
          <table style={{ marginBottom: 24 }}>
            <thead>
              <tr>
                <th>#</th>
                <th>Description</th>
                <th>Qty</th>
                <th>Unit Price</th>
                <th style={{ textAlign: 'right' }}>Total</th>
              </tr>
            </thead>
            <tbody>
              {invoice.items.map((item, i) => (
                <tr key={i}>
                  <td style={{ color: 'var(--text-dim)', fontSize: 12 }}>{i + 1}</td>
                  <td>{item.description}</td>
                  <td style={{ color: 'var(--text-muted)' }}>{item.quantity}</td>
                  <td style={{ color: 'var(--text-muted)' }}>PKR {item.unitPrice.toLocaleString()}</td>
                  <td style={{ textAlign: 'right', fontWeight: 600 }}>PKR {item.total.toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
          </table>

          {/* Totals */}
          <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
            <div style={{ minWidth: 260 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 0', fontSize: 14, color: 'var(--text-muted)' }}>
                <span>Subtotal</span><span>PKR {invoice.subtotal.toLocaleString()}</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 0', fontSize: 14, color: 'var(--text-muted)' }}>
                <span>Tax</span><span>PKR {invoice.tax.toLocaleString()}</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '14px 0', borderTop: '2px solid var(--accent)', marginTop: 8 }}>
                <span style={{ fontFamily: 'Syne', fontWeight: 700, fontSize: 18 }}>Total</span>
                <span style={{ fontFamily: 'Syne', fontWeight: 800, fontSize: 22, color: 'var(--green)' }}>PKR {invoice.total.toLocaleString()}</span>
              </div>
            </div>
          </div>

          {/* Notes */}
          {invoice.notes && (
            <div style={{ marginTop: 24, padding: 16, background: 'var(--surface2)', borderRadius: 'var(--radius-sm)', borderLeft: '3px solid var(--accent)' }}>
              <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: 6 }}>Notes</div>
              <p style={{ fontSize: 13, color: 'var(--text-muted)', lineHeight: 1.6 }}>{invoice.notes}</p>
            </div>
          )}
        </div>

        <div style={{ padding: '16px 32px', borderTop: '1px solid var(--border)', textAlign: 'center', fontSize: 12, color: 'var(--text-dim)' }}>
          Thank you for your business! · Generated by CRM Pro
        </div>
      </div>
    </div>
  );
}
